const errorCodes = {
  // validation error
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_QUERY_PARAMETER: "INVALID_QUERY_PARAMETER",
  INVALID_SORT_FIELD: "INVALID_SORT_FIELD",

  // resource error
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXIST",

  // Authentication
  UNAUTHORIZED: "UNAUTHORIZED",

  // Authorization
  FORBIDDEN: "FORBIDDEN",

  // Database
  DATABASE_ERROR: "DATABASE_ERROR",

  // Server
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};

export default errorCodes;
